// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.7
// source: anyns_api_server.proto

package anyns_api_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameAvailableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name including .any suffix
	FullName string `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
}

func (x *NameAvailableRequest) Reset() {
	*x = NameAvailableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anyns_api_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameAvailableRequest) ProtoMessage() {}

func (x *NameAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anyns_api_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameAvailableRequest.ProtoReflect.Descriptor instead.
func (*NameAvailableRequest) Descriptor() ([]byte, []int) {
	return file_anyns_api_server_proto_rawDescGZIP(), []int{0}
}

func (x *NameAvailableRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type NameAvailableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *NameAvailableResponse) Reset() {
	*x = NameAvailableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_anyns_api_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameAvailableResponse) ProtoMessage() {}

func (x *NameAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anyns_api_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameAvailableResponse.ProtoReflect.Descriptor instead.
func (*NameAvailableResponse) Descriptor() ([]byte, []int) {
	return file_anyns_api_server_proto_rawDescGZIP(), []int{1}
}

func (x *NameAvailableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_anyns_api_server_proto protoreflect.FileDescriptor

var file_anyns_api_server_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x6e, 0x79, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x14, 0x4e, 0x61, 0x6d, 0x65,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x15,
	0x4e, 0x61, 0x6d, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x32, 0x4b, 0x0a, 0x05, 0x41, 0x6e, 0x79, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x0f,
	0x49, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x15, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x15, 0x5a, 0x13, 0x70, 0x62, 0x2f, 0x61, 0x6e, 0x79, 0x6e, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_anyns_api_server_proto_rawDescOnce sync.Once
	file_anyns_api_server_proto_rawDescData = file_anyns_api_server_proto_rawDesc
)

func file_anyns_api_server_proto_rawDescGZIP() []byte {
	file_anyns_api_server_proto_rawDescOnce.Do(func() {
		file_anyns_api_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_anyns_api_server_proto_rawDescData)
	})
	return file_anyns_api_server_proto_rawDescData
}

var file_anyns_api_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anyns_api_server_proto_goTypes = []interface{}{
	(*NameAvailableRequest)(nil),  // 0: NameAvailableRequest
	(*NameAvailableResponse)(nil), // 1: NameAvailableResponse
}
var file_anyns_api_server_proto_depIdxs = []int32{
	0, // 0: Anyns.IsNameAvailable:input_type -> NameAvailableRequest
	1, // 1: Anyns.IsNameAvailable:output_type -> NameAvailableResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anyns_api_server_proto_init() }
func file_anyns_api_server_proto_init() {
	if File_anyns_api_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_anyns_api_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameAvailableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_anyns_api_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameAvailableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_anyns_api_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anyns_api_server_proto_goTypes,
		DependencyIndexes: file_anyns_api_server_proto_depIdxs,
		MessageInfos:      file_anyns_api_server_proto_msgTypes,
	}.Build()
	File_anyns_api_server_proto = out.File
	file_anyns_api_server_proto_rawDesc = nil
	file_anyns_api_server_proto_goTypes = nil
	file_anyns_api_server_proto_depIdxs = nil
}
