name: Deploy anyns-frontend

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  deploy-anyns-frontend:
    runs-on: [self-hosted, landing]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write .env file
        run: echo "${{ secrets.ANYNS_FRONTEND_DOTENV }}" > ./anyns-frontend/.env

      - name: Build image
        run: |
          docker buildx build \
            --tag anyns-frontend \
            --file Dockerfile \
            .

      - name: Remove running container
        run: |
          docker rm -f anyns-frontend

      - name: Run container from image
        run: |
          docker run -d -p 3000:3000 --name anyns-frontend anyns-frontend
